### ISSUE TITLE
Needs to for project

### ISSUE THREAD

**Issue by SevcanAlkan** [Feelfree2code/Raspberry-Ambient-Lighting#7]
- [x] Raspberry Pi
- [x] Breadboard
- [x] Jumper cables
- [x] 5x addressable led

**Comment by SevcanAlkan** [comment]
We need 5x led to building simple prototype. We can use a led strip or multiple standalone LEDs.

**Comment by kagankuscu** [comment]
5x led is cost 6,50 lv.
